SELECT 
  p.[ProductKey], 
  p.[ProductAlternateKey], 
  --[ProductSubcategoryKey],
  --[ProductCategoryKey],
  --[WeightUnitMeasureCode], 
  --[SizeUnitMeasureCode], 
  p.[EnglishProductName] as ProductName,
  ps.EnglishProductSubcategoryName as SubCategory,
  pc.EnglishProductCategoryName as Category,
  --[SpanishProductName], 
  --[FrenchProductName], 
  --[StandardCost], 
  --[FinishedGoodsFlag], 
  p.[Color], 
  --[SafetyStockLevel], 
  --[ReorderPoint], 
  --[ListPrice], 
  p.[Size], 
  --[SizeRange], 
  --[Weight], 
  --[DaysToManufacture], 
  p.[ProductLine], 
  --[DealerPrice], 
  --[Class], 
  --[Style], 
  p.[ModelName], 
  --[LargePhoto], 
  p.[EnglishDescription], 
  --[FrenchDescription], 
  --[ChineseDescription], 
  --[ArabicDescription], 
  --[HebrewDescription], 
  --[ThaiDescription], 
  --[GermanDescription], 
  --[JapaneseDescription], 
  --[TurkishDescription], 
  --[StartDate], 
  --[EndDate], 
  --[Status],
  ISNULL(p.Status, 'Outdated') as ProductStatus
FROM 
  [AdventureWorksDW2019].[dbo].[DimProduct] p
LEFT JOIN [AdventureWorksDW2019].[dbo].DimProductSubcategory ps ON p.ProductSubcategoryKey = ps.ProductSubcategoryKey
LEFT JOIN [AdventureWorksDW2019].[dbo].DimProductCategory pc ON ps.ProductCategoryKey = pc.ProductCategoryKey
ORDER BY p.ProductKey ASC
